version: '3.8'

services:
  vivien-server:
    build: .
    image: vivien-server
    container_name: vivien-server
    ports:
      - "8080:8080"
    volumes:
      - ./vivien-conf:/app/conf
      - ./vivien-data:/app/data
    restart: no