# Vivien Server Konfiguration
mode = "local"

# Das Git-Repository, auf dem Vivien arbeiten soll
remote = "Origin"
git.url = "{URL}"
git.branch = "master"
repo_path = "{REPO}"
git.user = "{USER}"
git.token = "{PASS}"
git.resolve = "ours"
engine_plugin = "Unity"

[server]
host = "localhost"
port = 8080
security = "lax"
# Das Secret muss für den Produktiv Einsatz ein zufällig generierter Hash sein.
secret = "vivien"
user = "admin"
#password = ""

[preview]
output = "jpg"
compression = 0.5

[views.artist]
writes = [ "/Assets/" ]
excludes = [ ".idea/", "*.meta" ]

[views.admin]
excludes = [ ".idea/", "*.meta" ]