# Vivien Server Konfiguration
# Letzte Änderung: 07.10.2026

# Der Mode bestimmt
# local - Einzel Benutzer Betrieb für eine lokale Installation.
# hosted - Mehr-Benutzer Betrieb für eine Server Installation.
# setup - Erzwingt einen eingeschränkten Start und öffnet die Konfig über das Web Interface.
mode = "local"

# Das Git-Repository, auf dem Vivien arbeiten soll
git.url = "<GIT_URL>"
git.user = "<Git_USER>"
git.token = "<GIT_PASS>"
git.remote = "origin"
git.branch = "master"

# Git Konflikt Verarbeitung
# Siehe git Dokumentation: https://git-scm.com/docs/merge-strategies
git.resolve = "ours"

# Der lokale Pfad für das Repository. Wird angelegt, wenn nicht vorhanden.
repo_path = "<REPOSITORY>"

# Aktiviert ein zusätzliche Plugin für die Bearbeitung von Gameengine verwaltete Ressourcen.
# Unity - Unity ab Version 6
# Godot - (Nicht implementiert)
engine_plugin = "Unity"

[server]
host = "localhost"
port = 8080

# Sicherheitsrichtlinie
# lax - Erlaubt Cross Site Requests
# strict - Strengere Richtlinie ohne Cross Site Requests
security = "lax"

# Server Secret für die Verschlüsslung von JWT-Sessions.
# Falls nicht gesetzt, generiert Vivien automatisch ein nicht persistentes Secret bei Server start.
secret = "Vivien"

# Benutzer Whitelist (Optional)
# Wenn gesetzt, sind nur die hier aufgeführten Benutzer erlaubt.
# Der Benutzername kann im Client frei gewählt werden. Das ist kein echter Schutzmechanismus!
#users = [ "Anna", "Fufu" ]

# Passwort Schutz des Servers
#password = ""

# Erlaubte Upload Formate (Optional)
formats = "png,jpg,jpeg,tif,tiff,tga,txt,md,json,yaml,wav,mp3,acc,ogg,fbx,glb,gltf,obj,mtl"

[preview]
# Das Image Format für die Vorschau von Bilddateien.
# Muss ein von Image.IO unterstütztes Format sein.
output = "jpg"

# Komprimierung für Bilder Vorschau
compression = 0.5


# Views steuern die Anzeige von Menüelementen und Dateien.
# Außerdem kann hierüber ein Schreibschutz für bestimmte Dateien eingestellt werden.
# admin - Uneingeschränkte Oberfläche
# artist - Redizierte Oberfläche
[views.admin]
excludes = [ ".meta" ]

[views.artist]
# Schreibbare Ordner
writes = [ "/Assets/" ]
# Sichtbare Ordner und Dateien
includes = [ "*.png", "*.jpg", "*.tga", "*.tif", "*.svg", "*.md", "*.txt", "*.json", "*.yaml", "*.fbx", "*.obj", "*.gltf", "*.glb", "*.wav", "*.mp3", "*.ogg", "*.aac" ]
excludes = [ ".idea/", ".git/", ".meta" ]
